server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-duhmbd9s.sql.tencentcdb.com:22592/huacai?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: huacai
    password: Pass1234
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

#图片上传
web:
  uploadpath: /images/  #图片上传路径
  load-path: file:/images/  #图片访问路径

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_empty

Wechat:
  Applets:
    appId: wx5dc509c6393bc09e
    appSecret: 3aaaf06af17fe4e4b80be3a7d56b3970
